import { Component } from '@angular/core';
import { ReplaySubject, throwError, of } from 'rxjs';
import { retry, catchError } from 'rxjs/operators';

import { ExerciseService } from '../exercise.service';

@Component({
  selector: 'rxw-error-handling',
  templateUrl: './error-handling.component.html',
})
export class ErrorHandlingComponent {

  logStream$ = new ReplaySubject();

  constructor(private es: ExerciseService) { }

  start() {
    this.es.randomError().pipe(
      retry(2),
      // catchError(err => throwError('This was an error...'))
      catchError(() => of('Was there an error?'))
    ).subscribe({
      next: value => this.logStream$.next(value),
      error: err => this.logStream$.next('ðŸ’¥ ERROR: ' + err)
    });
  }
}
